### PR TITLE
Follow visit redirects by issuing a "replace" visit with the redirected-to location

### PR DESCRIPTION
**Pull request by jayohms**
This addresses: https://github.com/hotwired/turbo-android/issues/128

Detect when a visit redirect occurs and propose a new visit with the new url. The original destination `Fragment` (before the redirect) is replaced with the resulting destination `Fragment` (after the redirect) through the normal visit flow. This allows the path configuration to work for the redirected-to url path and the destination `Fragment.location` (which is immutable) is accurate on the navigation stack.

I added a way to test visit redirects in the demo site: https://github.com/hotwired/turbo-native-demo/pull/2

### CODE REVIEW

**Comment by jayohms** [comment]
@zachwaugh @sstephenson I'd like to get your feedback on this. This has been a longstanding problem in Turbolinks, but now that we can detect redirected visits in Turbo, we can handle redirects in a more elegant, predictable way. 

Is `visitRequestCompleted()` the best place to inspect when a visit redirect has occurred? Does the iOS app have this same issue? This solution works great in the Android app, but I want to make sure that we solve this in a consistent way in the mobile apps.

**Comment by zachwaugh** [comment]
The iOS app has the same exact issue. My first thought is we just need to detect the new url, so things like pull-to-refresh work correctly, but I hadn't considered we might have the wrong path properties too. So I agree doing a replace with the redirected location makes the most sense.

I'm wondering if it should come through as new proposal with an `action` or `options` that indicate it's a `redirect`? That way it would work like all other visits and also include the responseHTML too, since we would have already completed the redirect at that point. The only edge case then would be if the redirected location should be presented as a modal, and we'd already have pushed a new visit on the navigation stack that is now empty. But we could detect that and handle it.

**Comment by sstephenson** [comment]
I think we should actually just change this in Turbo. Top-level form submissions should result in a replace visit to the redirected URL.

**Comment by jayohms** [comment]
@sstephenson This isn't always going to be the result of a form submission. In fact, it likely won't be the result of a form submission because `modal` screens already handle form redirects appropriately. 

The main issue is with `GET` requests like: https://github.com/hotwired/turbo-native-demo/pull/2

Or am I misunderstanding something?

**Comment by sstephenson** [comment]
My mistake, I see this handles visits that redirect. Still, I wonder if we can make a change to Turbo instead. Haven't thought this through fully, but maybe redirected visits shouldn't render, and [Visit#followRedirect](https://github.com/hotwired/turbo/blob/4a6c9a50e1c0548ec975a6f03241a7e196400a73/src/core/drive/visit.ts#L247-L253) can propose a new replace visit with the received response?

**Comment by jayohms** [comment]
No problem, and moving it into the library would be fine with me. You're thinking that the browser and mobile apps should behave the same exact way and let Turbo propose a `replace` visit with the redirected response?

That works for me as long as `visitCompleted()` and `visitRendered()` are bypassed for the original visit (before the redirect and `replace` visit).

**Comment by sstephenson** [comment]
I'm thinking you'd still get visitCompleted, and then a redirect visit proposal right afterwards, but yeah, there'd be no visitRendered for the original visit. I'll get a branch going for this and report back 👍

**Comment by jayohms** [comment]
Perfect, thank you 👍

**Pull request closed without merging**
